# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abattoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, help_text='Numéro unique du bon de commande (généré automatiquement)', max_length=50, unique=True, verbose_name='Numéro de bon')),
                ('type_quantite', models.CharField(choices=[('NOMBRE', 'Nombre de bêtes'), ('POIDS', 'Kilogrammes')], default='NOMBRE', max_length=10, verbose_name='Type de quantité')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Nombre de bêtes ou kilogrammes selon le type', max_digits=10, verbose_name='Quantité')),
                ('type_bete', models.CharField(choices=[('BOVIN', 'Bovin'), ('OVIN', 'Ovin'), ('CAPRIN', 'Caprin')], max_length=10, verbose_name='Type de bête')),
                ('type_produit', models.CharField(choices=[('CARCASSE', 'Carcasse'), ('VIF', 'Vif')], max_length=10, verbose_name='Type de produit')),
                ('avec_cinquieme_quartier', models.BooleanField(default=False, help_text='Inclure le cinquième quartier (abats)', verbose_name='Avec cinquième quartier')),
                ('source', models.CharField(choices=[('PRODUCTION', 'Production'), ('ABATTOIR', 'Abattoir')], default='ABATTOIR', help_text='Source du bon de commande : Production ou Abattoir', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, help_text='Notes et remarques sur la commande', verbose_name='Notes')),
                ('versement', models.DecimalField(blank=True, decimal_places=2, help_text='Montant versé par le client (en DA)', max_digits=10, null=True, verbose_name='Versement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRME', 'Confirmé'), ('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('date_livraison_reelle', models.DateField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('abattoir', models.ForeignKey(help_text="Abattoir d'attribution (si source=Production) ou abattoir source (si source=Abattoir)", on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='abattoir.abattoir', verbose_name='Abattoir')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-created_at'],
            },
        ),
    ]
