# Generated by Django 4.2.23 on 2025-10-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0008_alter_stabulation_numero_stabulation'),
        ('bon_commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='source',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('ABATTOIR', 'Abattoir')], default='ABATTOIR', help_text='Source du bon de commande : Production ou Abattoir', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='versement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant versé par le client (en DA)', max_digits=10, null=True, verbose_name='Versement'),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='abattoir',
            field=models.ForeignKey(help_text="Abattoir d'attribution (si source=Production) ou abattoir source (si source=Abattoir)", on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='abattoir.abattoir', verbose_name='Abattoir'),
        ),
    ]
