# Generated by Django 4.2.23 on 2025-10-25 01:44

import django.core.validators
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReception',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_reception', models.CharField(blank=True, db_index=True, help_text="Numéro unique d'identification de la réception (généré automatiquement)", max_length=50, verbose_name='Numéro de réception')),
                ('nombre_betes_attendues', models.PositiveIntegerField(help_text='Nombre de bêtes attendues selon le transfert', verbose_name='Nombre de bêtes attendues')),
                ('nombre_betes_recues', models.PositiveIntegerField(default=0, help_text='Nombre de bêtes effectivement reçues', verbose_name='Nombre de bêtes reçues')),
                ('nombre_betes_manquantes', models.PositiveIntegerField(default=0, help_text='Nombre de bêtes manquantes', verbose_name='Nombre de bêtes manquantes')),
                ('betes_manquantes', models.JSONField(blank=True, default=list, help_text='Liste des numéros de boucles des bêtes manquantes', verbose_name='Bêtes manquantes')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('RECU', 'Reçu'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut actuel de la réception', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, help_text='Date et heure de création de la réception', verbose_name='Date de création')),
                ('date_reception', models.DateTimeField(blank=True, help_text='Date et heure de réception effective', null=True, verbose_name='Date de réception')),
                ('date_annulation', models.DateTimeField(blank=True, help_text="Date et heure d'annulation de la réception", null=True, verbose_name="Date d'annulation")),
                ('note', models.TextField(blank=True, help_text='Notes et observations sur la réception', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Réceptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransfert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_transfert', models.CharField(blank=True, db_index=True, help_text="Numéro unique d'identification du transfert (généré automatiquement)", max_length=50, verbose_name='Numéro de transfert')),
                ('nombre_betes', models.PositiveIntegerField(help_text='Nombre total de bêtes à transférer', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de bêtes')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', help_text='Statut actuel du transfert', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, help_text='Date et heure de création du transfert', verbose_name='Date de création')),
                ('date_livraison', models.DateTimeField(blank=True, help_text='Date et heure de livraison effective', null=True, verbose_name='Date de livraison')),
                ('date_annulation', models.DateTimeField(blank=True, help_text="Date et heure d'annulation du transfert", null=True, verbose_name="Date d'annulation")),
                ('motif', models.TextField(blank=True, help_text='Raison du transfert de bêtes', null=True, verbose_name='Motif du transfert')),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur le transfert', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Transferts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reception', models.CharField(blank=True, help_text="Numéro unique d'identification de la réception (généré automatiquement)", max_length=50, unique=True, verbose_name='Numéro de réception')),
                ('nombre_betes_attendues', models.PositiveIntegerField(help_text='Nombre de bêtes attendues selon le transfert', verbose_name='Nombre de bêtes attendues')),
                ('nombre_betes_recues', models.PositiveIntegerField(default=0, help_text='Nombre de bêtes effectivement reçues', verbose_name='Nombre de bêtes reçues')),
                ('nombre_betes_manquantes', models.PositiveIntegerField(default=0, help_text='Nombre de bêtes manquantes', verbose_name='Nombre de bêtes manquantes')),
                ('betes_manquantes', models.JSONField(blank=True, default=list, help_text='Liste des numéros de boucles des bêtes manquantes', verbose_name='Bêtes manquantes')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('RECU', 'Reçu'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut actuel de la réception', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création de la réception', verbose_name='Date de création')),
                ('date_reception', models.DateTimeField(blank=True, help_text='Date et heure de réception effective', null=True, verbose_name='Date de réception')),
                ('date_annulation', models.DateTimeField(blank=True, help_text="Date et heure d'annulation de la réception", null=True, verbose_name="Date d'annulation")),
                ('note', models.TextField(blank=True, help_text='Notes et observations sur la réception', null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transfert', models.CharField(blank=True, help_text="Numéro unique d'identification du transfert (généré automatiquement)", max_length=50, unique=True, verbose_name='Numéro de transfert')),
                ('nombre_betes', models.PositiveIntegerField(help_text='Nombre total de bêtes à transférer', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de bêtes')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', help_text='Statut actuel du transfert', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du transfert', verbose_name='Date de création')),
                ('date_livraison', models.DateTimeField(blank=True, help_text='Date et heure de livraison effective', null=True, verbose_name='Date de livraison')),
                ('date_annulation', models.DateTimeField(blank=True, help_text="Date et heure d'annulation du transfert", null=True, verbose_name="Date d'annulation")),
                ('motif', models.TextField(blank=True, help_text='Raison du transfert de bêtes', null=True, verbose_name='Motif du transfert')),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur le transfert', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TransfertBete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Bête de transfert',
                'verbose_name_plural': 'Bêtes de transfert',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
