# Generated by Django 4.2.23 on 2025-10-20 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0008_alter_stabulation_numero_stabulation'),
        ('bete', '0006_historicalbete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transfert', models.CharField(max_length=50, unique=True, verbose_name='Numéro de transfert')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abattoir_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='abattoir.abattoir', verbose_name='Abattoir destinataire')),
                ('abattoir_expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_expedies', to='abattoir.abattoir', verbose_name='Abattoir expéditeur')),
                ('betes', models.ManyToManyField(related_name='transferts', to='bete.bete', verbose_name='Bêtes transférées')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-created_at'],
            },
        ),
    ]
