# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bete', '0003_initial'),
        ('abattoir', '0002_initial'),
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertbete',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a ajouté cette bête au transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='transfertbete',
            name='bete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bete.bete', verbose_name='Bête'),
        ),
        migrations.AddField(
            model_name='transfertbete',
            name='transfert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfert.transfert', verbose_name='Transfert'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='abattoir_destinataire',
            field=models.ForeignKey(help_text='Abattoir qui reçoit les bêtes', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_recus', to='abattoir.abattoir', verbose_name='Abattoir destinataire'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='abattoir_expediteur',
            field=models.ForeignKey(help_text='Abattoir qui envoie les bêtes', on_delete=django.db.models.deletion.CASCADE, related_name='transferts_expedies', to='abattoir.abattoir', verbose_name='Abattoir expéditeur'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='annule_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a annulé le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='betes',
            field=models.ManyToManyField(help_text='Bêtes incluses dans ce transfert', through='transfert.TransfertBete', to='bete.bete', verbose_name='Bêtes à transférer'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le transfert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='reception',
            name='annule_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a annulé la réception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='reception',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la réception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='reception',
            name='transfert',
            field=models.OneToOneField(help_text='Transfert associé à cette réception', on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='transfert.transfert', verbose_name='Transfert'),
        ),
        migrations.AddField(
            model_name='reception',
            name='valide_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé la réception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='abattoir_destinataire',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Abattoir qui reçoit les bêtes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='abattoir.abattoir', verbose_name='Abattoir destinataire'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='abattoir_expediteur',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Abattoir qui envoie les bêtes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='abattoir.abattoir', verbose_name='Abattoir expéditeur'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='annule_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a annulé le transfert', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='cree_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a créé le transfert', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='valide_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a validé le transfert', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='historicalreception',
            name='annule_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a annulé la réception', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='historicalreception',
            name='cree_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a créé la réception', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='historicalreception',
            name='transfert',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Transfert associé à cette réception', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transfert.transfert', verbose_name='Transfert'),
        ),
        migrations.AddField(
            model_name='historicalreception',
            name='valide_par',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur qui a validé la réception', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterUniqueTogether(
            name='transfertbete',
            unique_together={('transfert', 'bete')},
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['abattoir_expediteur', 'statut'], name='transfert_t_abattoi_0a5dab_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['abattoir_destinataire', 'statut'], name='transfert_t_abattoi_ae118a_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['date_creation'], name='transfert_t_date_cr_21600c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfert',
            index=models.Index(fields=['statut'], name='transfert_t_statut_054c97_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['date_creation'], name='transfert_r_date_cr_087c76_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['statut'], name='transfert_r_statut_2b6e01_idx'),
        ),
    ]
