# Generated by Django 4.2.23 on 2025-10-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreception',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ROUTE', 'En route'), ('EN_COURS', 'En cours'), ('RECU', 'Reçu'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut actuel de la réception', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', help_text='Statut actuel du transfert', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ROUTE', 'En route'), ('EN_COURS', 'En cours'), ('RECU', 'Reçu'), ('PARTIEL', 'Partiel'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut actuel de la réception', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', help_text='Statut actuel du transfert', max_length=20, verbose_name='Statut'),
        ),
    ]
