# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abattoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_boucle', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'identification")),
                ('num_boucle_post_abattage', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'identification post abattage")),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe')),
                ('poids_vif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids actuel (kg)')),
                ('poids_a_chaud', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a chaud (kg)')),
                ('poids_a_froid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a froid (kg)')),
                ('statut', models.CharField(choices=[('VIVANT', 'Vivant'), ('EN_STABULATION', 'En stabulation'), ('ABATTU', 'Abattu'), ('MORT', 'Mort'), ('VENDU', 'Vendu')], default='VIVANT', max_length=20, verbose_name='Statut')),
                ('etat_sante', models.CharField(choices=[('BON', 'BON'), ('MALADE', 'MALADE')], default='BON', max_length=10, verbose_name='Etat de santé')),
                ('abattage_urgence', models.BooleanField(default=False, verbose_name='Abattage urgent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Bête',
                'verbose_name_plural': 'Bêtes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'espèce")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBete',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('num_boucle', models.CharField(db_index=True, max_length=50, verbose_name="Numéro d'identification")),
                ('num_boucle_post_abattage', models.CharField(db_index=True, max_length=50, verbose_name="Numéro d'identification post abattage")),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe')),
                ('poids_vif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids actuel (kg)')),
                ('poids_a_chaud', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a chaud (kg)')),
                ('poids_a_froid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a froid (kg)')),
                ('statut', models.CharField(choices=[('VIVANT', 'Vivant'), ('EN_STABULATION', 'En stabulation'), ('ABATTU', 'Abattu'), ('MORT', 'Mort'), ('VENDU', 'Vendu')], default='VIVANT', max_length=20, verbose_name='Statut')),
                ('etat_sante', models.CharField(choices=[('BON', 'BON'), ('MALADE', 'MALADE')], default='BON', max_length=10, verbose_name='Etat de santé')),
                ('abattage_urgence', models.BooleanField(default=False, verbose_name='Abattage urgent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('abattoir', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='abattoir.abattoir', verbose_name='Abattoir')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Bêtes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
