# Generated by Django 4.2.23 on 2025-10-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bete',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betes_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='bete',
            name='espece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bete.espece', verbose_name='Espèce'),
        ),
        migrations.AddField(
            model_name='bete',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bete.race', verbose_name='Race'),
        ),
        migrations.AddField(
            model_name='bete',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ALIMENT_SHEPTEL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='alimentation',
            name='aliment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bete.aliment', verbose_name='Aliment'),
        ),
        migrations.AddField(
            model_name='alimentation',
            name='bete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bete.bete', verbose_name='Bête'),
        ),
        migrations.AddField(
            model_name='alimentation',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'user_type': 'ALIMENT_SHEPTEL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together={('nom', 'espece')},
        ),
    ]
