# Generated by Django 5.0.8 on 2025-10-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0002_initial'),
        ('bete', '0002_initial'),
        ('client', '0002_alter_client_type_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentation',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='alimentation',
            name='bete',
        ),
        migrations.RemoveField(
            model_name='alimentation',
            name='responsable',
        ),
        migrations.AlterUniqueTogether(
            name='race',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='race',
            name='espece',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='race',
        ),
        migrations.RenameField(
            model_name='bete',
            old_name='numero_identification',
            new_name='num_boucle',
        ),
        migrations.RenameField(
            model_name='bete',
            old_name='poids_actuel',
            new_name='poids_vif',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='proprietaire_origine',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='responsable',
        ),
        migrations.AddField(
            model_name='bete',
            name='abattage_urgence',
            field=models.BooleanField(default=False, verbose_name='Abattage urgent'),
        ),
        migrations.AddField(
            model_name='bete',
            name='abattoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abattoir.abattoir', verbose_name='Abattoir'),
        ),
        migrations.AddField(
            model_name='bete',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='bete',
            name='etat_sante',
            field=models.CharField(choices=[('BON', 'BON'), ('MALADE', 'MALADE')], default='BON', max_length=10, verbose_name='Etat de santé'),
        ),
        migrations.AddField(
            model_name='bete',
            name='num_boucle_post_abattage',
            field=models.CharField(default=3, max_length=50, unique=True, verbose_name="Numéro d'identification post abattage"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bete',
            name='poids_a_chaud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a chaud (kg)'),
        ),
        migrations.AddField(
            model_name='bete',
            name='poids_a_froid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a froid (kg)'),
        ),
        migrations.DeleteModel(
            name='Aliment',
        ),
        migrations.DeleteModel(
            name='Alimentation',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
