# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0002_initial'),
        ('client', '0001_initial'),
        ('bete', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbete',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='historicalbete',
            name='espece',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bete.espece', verbose_name='Espèce'),
        ),
        migrations.AddField(
            model_name='bete',
            name='abattoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abattoir.abattoir', verbose_name='Abattoir'),
        ),
        migrations.AddField(
            model_name='bete',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='bete',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betes_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='bete',
            name='espece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bete.espece', verbose_name='Espèce'),
        ),
    ]
