# Generated by Django 5.0.8 on 2025-10-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bete', '0003_remove_alimentation_aliment_remove_alimentation_bete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bete',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='bete',
            name='poids_naissance',
        ),
    ]
