# Generated by Django 4.2.23 on 2025-10-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bete', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bete',
            name='num_boucle_post_abattage',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro d'identification post abattage"),
        ),
        migrations.AlterField(
            model_name='historicalbete',
            name='num_boucle_post_abattage',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name="Numéro d'identification post abattage"),
        ),
    ]
