# Generated by Django 4.2.23 on 2025-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bete', '0004_remove_bete_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bete',
            name='statut',
            field=models.CharField(choices=[('VIVANT', 'Vivant'), ('EN_STABULATION', 'En stabulation'), ('ABATTU', 'Abattu'), ('MORT', 'Mort'), ('VENDU', 'Vendu')], default='VIVANT', max_length=20, verbose_name='Statut'),
        ),
    ]
