# Generated by Django 4.2.23 on 2025-10-19 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0008_alter_stabulation_numero_stabulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_remove_facture_commande_remove_facture_created_by_and_more'),
        ('bete', '0005_alter_bete_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBete',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('num_boucle', models.CharField(db_index=True, max_length=50, verbose_name="Numéro d'identification")),
                ('num_boucle_post_abattage', models.CharField(db_index=True, max_length=50, verbose_name="Numéro d'identification post abattage")),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe')),
                ('poids_vif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids actuel (kg)')),
                ('poids_a_chaud', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a chaud (kg)')),
                ('poids_a_froid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Poids a froid (kg)')),
                ('statut', models.CharField(choices=[('VIVANT', 'Vivant'), ('EN_STABULATION', 'En stabulation'), ('ABATTU', 'Abattu'), ('MORT', 'Mort'), ('VENDU', 'Vendu')], default='VIVANT', max_length=20, verbose_name='Statut')),
                ('etat_sante', models.CharField(choices=[('BON', 'BON'), ('MALADE', 'MALADE')], default='BON', max_length=10, verbose_name='Etat de santé')),
                ('abattage_urgence', models.BooleanField(default=False, verbose_name='Abattage urgent')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de modification')),
                ('history_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('abattoir', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='abattoir.abattoir', verbose_name='Abattoir')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('espece', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bete.espece', verbose_name='Espèce')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'historical Bêtes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
