# Generated by Django 4.2.23 on 2025-10-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0008_alter_stabulation_numero_stabulation'),
        ('transfert', '0001_initial'),
        ('bete', '0006_historicalbete'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTransfertBete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(auto_now_add=True, verbose_name='Date du transfert')),
                ('statut_transfert', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20, verbose_name='Statut du transfert')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('abattoir_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='abattoir.abattoir', verbose_name='Abattoir destination')),
                ('abattoir_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='abattoir.abattoir', verbose_name='Abattoir source')),
                ('bete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_transferts', to='bete.bete', verbose_name='Bête')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_betes', to='transfert.transfert', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'Historique de transfert de bête',
                'verbose_name_plural': 'Historiques de transferts de bêtes',
                'ordering': ['-date_transfert'],
                'unique_together': {('bete', 'transfert')},
            },
        ),
    ]
