# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abattoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('STABULATION_CREATED', 'Stabulation créée'), ('STABULATION_TERMINATED', 'Stabulation terminée'), ('BON_COMMANDE_CREATED', 'Bon de commande créé'), ('BON_COMMANDE_CONFIRMED', 'Bon de commande confirmé'), ('BON_COMMANDE_STATUS_CHANGED', 'Statut bon de commande modifié'), ('TRANSFERT_CREATED', 'Transfert créé'), ('TRANSFERT_DELIVERED', 'Transfert livré'), ('ABATTOIR_UPDATED', 'Abattoir modifié')], help_text="Type d'événement qui a déclenché la notification", max_length=50, verbose_name='Type de notification')),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text='Message détaillé de la notification', verbose_name='Message')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='MEDIUM', help_text='Niveau de priorité de la notification', max_length=10, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, help_text="Indique si la notification a été lue par l'utilisateur", verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date et heure de lecture de la notification', null=True, verbose_name='Date de lecture')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires liées à la notification (JSON)', verbose_name='Données contextuelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('abattoir', models.ForeignKey(blank=True, help_text='Abattoir concerné par la notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='abattoir.abattoir', verbose_name='Abattoir')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
