# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification', 'created_at'], name='notificatio_type_no_38f9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['abattoir', 'created_at'], name='notificatio_abattoi_8fbb08_idx'),
        ),
    ]
