# Generated by Django 4.2.23 on 2025-10-12 14:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('type_client', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hôtel'), ('SUPERMARCHE', 'Supermarché'), ('GROSSISTE', 'Grossiste'), ('AUTRE', 'Autre')], default='PARTICULIER', max_length=15, verbose_name='Type de client')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Limite de crédit (DA)')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde actuel (DA)')),
                ('contact_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact principal')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du contact')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commercial', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SUPERVISEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Commercial responsable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateTimeField(verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateTimeField(verbose_name='Date de livraison prévue')),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=15, verbose_name='Statut')),
                ('type_paiement', models.CharField(choices=[('COMPTANT', 'Comptant'), ('CREDIT', 'Crédit'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], default='COMPTANT', max_length=10, verbose_name='Type de paiement')),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total (DA)')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise (DA)')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT (DA)')),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TVA (DA)')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC (DA)')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('instructions_livraison', models.TextField(blank=True, null=True, verbose_name='Instructions de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_facture', models.DateField(verbose_name='Date de facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Emise'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10, verbose_name='Statut')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant HT (DA)')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TVA (DA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant TTC (DA)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.commande', verbose_name='Commande')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité (kg)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (DA/kg)')),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remise ligne (DA)')),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total ligne (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commande', verbose_name='Commande')),
                ('decoupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abattoir.decoupe', verbose_name='Découpe')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['commande', 'id'],
                'unique_together': {('commande', 'decoupe')},
            },
        ),
    ]
