# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('type_client', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('SUPERGROSSISTE', 'Supergrossiste'), ('GROSSISTE', 'Grossiste')], default='PARTICULIER', max_length=15, verbose_name='Type de client')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name="NIF (Numéro d'Identification Fiscale)")),
                ('nis', models.CharField(blank=True, max_length=20, null=True, verbose_name="NIS (Numéro d'Identification Sociale)")),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('contact_principal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact principal')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du contact')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
