# Generated by Django 5.0.8 on 2025-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('SUPERMARCHE', 'Supermarché'), ('GROSSISTE', 'Grossiste')], default='PARTICULIER', max_length=15, verbose_name='Type de client'),
        ),
    ]
