# Generated by Django 4.2.23 on 2025-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_type_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='lignecommande',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='decoupe',
        ),
        migrations.RemoveField(
            model_name='client',
            name='limite_credit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='solde_actuel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='statut',
        ),
        migrations.AddField(
            model_name='client',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="NIF (Numéro d'Identification Fiscale)"),
        ),
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="NIS (Numéro d'Identification Sociale)"),
        ),
        migrations.AddField(
            model_name='client',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('PARTICULIER', 'Particulier'), ('SUPERGROSSISTE', 'Supergrossiste'), ('GROSSISTE', 'Grossiste')], default='PARTICULIER', max_length=15, verbose_name='Type de client'),
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='LigneCommande',
        ),
    ]
