# Generated by Django 4.2.23 on 2025-10-17 20:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import personnel.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0005_alter_abattoir_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('RESPONSABLE_ABATTOIR', "Responsable de l'abattoir"), ('RESPONSABLE_ABATTAGE', "Responsable d'abattage"), ('GESTIONNAIRE_STOCK', 'Gestionnaire de stock'), ('RH', 'Ressources Humaines'), ('COMPTABLE', 'Comptable'), ('SECURITE', 'Agent de sécurité'), ('MAINTENANCE', 'Agent de maintenance'), ('VETERINAIRE', 'Vétérinaire'), ('INSPECTEUR', 'Inspecteur'), ('OPERATEUR', 'Opérateur'), ('CHAUFFEUR', 'Chauffeur'), ('NETTOYAGE', 'Agent de nettoyage'), ('AUTRE', 'Autre')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom_complet', models.CharField(blank=True, max_length=201, verbose_name='Nom complet')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(default='Algérienne', max_length=50, verbose_name='Nationalité')),
                ('numero_carte_identite', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de carte d'identité doit contenir exactement 10 chiffres", regex='^\\d{10}$')], verbose_name="Numéro de carte d'identité")),
                ('date_emission_carte', models.DateField(verbose_name="Date d'émission de la carte")),
                ('lieu_emission_carte', models.CharField(max_length=100, verbose_name="Lieu d'émission de la carte")),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone algérien invalide', regex='^(\\+213|0)[5-7]\\d{8}$')], verbose_name='Téléphone')),
                ('telephone_urgence', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone algérien invalide', regex='^(\\+213|0)[5-7]\\d{8}$')], verbose_name="Téléphone d'urgence")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(max_length=50, verbose_name='Wilaya')),
                ('commune', models.CharField(max_length=50, verbose_name='Commune')),
                ('numero_employe', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'employé")),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu'), ('CONGE', 'En congé'), ('DEMISSION', 'Démission')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=personnel.models.personnel_photo_upload_path, verbose_name='Photo')),
                ('carte_identite_recto', models.ImageField(blank=True, null=True, upload_to=personnel.models.carte_identite_upload_path, verbose_name="Carte d'identité (recto)")),
                ('carte_identite_verso', models.ImageField(blank=True, null=True, upload_to=personnel.models.carte_identite_upload_path, verbose_name="Carte d'identité (verso)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('competences', models.JSONField(blank=True, default=list, verbose_name='Compétences')),
                ('formations', models.JSONField(blank=True, default=list, verbose_name='Formations')),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='abattoir.abattoir', verbose_name='Abattoir')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='personnel.role', verbose_name='Rôle')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('abattoir', 'numero_employe')},
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=200, verbose_name='Nom de la formation')),
                ('organisme', models.CharField(max_length=200, verbose_name='Organisme')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('duree_heures', models.IntegerField(verbose_name='Durée en heures')),
                ('certificat', models.FileField(blank=True, null=True, upload_to='personnel/certificats/', verbose_name='Certificat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_personnel', to='personnel.personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('CONSULTANT', 'Consultant')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('heures_semaine', models.IntegerField(default=40, verbose_name='Heures par semaine')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='personnel.personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('CONGE_ANNUEL', 'Congé annuel'), ('CONGE_MALADIE', 'Congé maladie'), ('CONGE_MATERNITE', 'Congé maternité'), ('CONGE_PATERNITE', 'Congé paternité'), ('ABSENCE_NON_JUSTIFIEE', 'Absence non justifiée'), ('CONGE_EXCEPTIONNEL', 'Congé exceptionnel'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'absence")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_jours', models.IntegerField(verbose_name='Nombre de jours')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='personnel/justificatifs/', verbose_name='Justificatif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='personnel.personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
    ]
