# Generated by Django 4.2.23 on 2025-10-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user_account',
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='Contrat',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
