# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='personnel.role', verbose_name='Rôle'),
        ),
        migrations.AlterUniqueTogether(
            name='personnel',
            unique_together={('abattoir', 'numero_employe')},
        ),
    ]
