# Generated by Django 4.2.23 on 2025-10-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0005_alter_abattoir_responsable'),
        ('users', '0002_user_device_fingerprint_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abattoir',
            field=models.ForeignKey(blank=True, help_text='Abattoir auquel cet utilisateur est assigné', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='abattoir.abattoir', verbose_name='Abattoir assigné'),
        ),
    ]
