# Generated by Django 4.2.23 on 2025-10-12 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_abattage', models.PositiveIntegerField(verbose_name="Ordre d'abattage")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('heure_abattage', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'abattage")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Abattage',
                'verbose_name_plural': 'Abattages',
                'ordering': ['session', 'ordre_abattage'],
            },
        ),
        migrations.CreateModel(
            name='Abattoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'abattoir")),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('capacite_reception_ovin', models.PositiveIntegerField(default=0, help_text="Nombre maximum d'ovins pouvant être reçus par jour", verbose_name='Capacité de réception Ovin')),
                ('capacite_reception_bovin', models.PositiveIntegerField(default=0, help_text='Nombre maximum de bovins pouvant être reçus par jour', verbose_name='Capacité de réception Bovin')),
                ('capacite_stabulation', models.PositiveIntegerField(default=0, help_text='Nombre maximum de bêtes pouvant être en stabulation', verbose_name='Capacité de stabulation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Abattoir',
                'verbose_name_plural': 'Abattoirs',
                'ordering': ['wilaya', 'commune', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Carcasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_carcasse', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids de la carcasse (kg)')),
                ('rendement', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Rendement (%)')),
                ('qualite', models.CharField(choices=[('EXCELLENTE', 'Excellente'), ('BONNE', 'Bonne'), ('MOYENNE', 'Moyenne'), ('MAUVAISE', 'Mauvaise')], max_length=10, verbose_name='Qualité')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Carcasse',
                'verbose_name_plural': 'Carcasses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decoupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_decoupe', models.CharField(choices=[('PRIME', 'Prime'), ('SECONDE', 'Seconde'), ('TROISIEME', 'Troisième'), ('ABATS', 'Abats')], max_length=10, verbose_name='Type de découpe')),
                ('nom_decoupe', models.CharField(max_length=100, verbose_name='Nom de la découpe')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids (kg)')),
                ('prix_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix au kg (DA)')),
                ('qualite', models.CharField(choices=[('EXCELLENTE', 'Excellente'), ('BONNE', 'Bonne'), ('MOYENNE', 'Moyenne'), ('MAUVAISE', 'Mauvaise')], max_length=10, verbose_name='Qualité')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Découpe',
                'verbose_name_plural': 'Découpes',
                'ordering': ['carcasse', 'type_decoupe', 'nom_decoupe'],
            },
        ),
        migrations.CreateModel(
            name='SessionAbattage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField(verbose_name='Date de la session')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abattoir.abattoir', verbose_name='Abattoir')),
            ],
            options={
                'verbose_name': "Session d'abattage",
                'verbose_name_plural': "Sessions d'abattage",
                'ordering': ['-date_session', '-heure_debut'],
            },
        ),
    ]
