# Generated by Django 4.2.23 on 2025-10-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abattoir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionabattage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='sessionabattage',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'user_type': 'SUPERVISEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Superviseur'),
        ),
        migrations.AddField(
            model_name='decoupe',
            name='carcasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abattoir.carcasse', verbose_name='Carcasse'),
        ),
        migrations.AddField(
            model_name='decoupe',
            name='decoupeur',
            field=models.ForeignKey(limit_choices_to={'user_type': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Découpeur'),
        ),
        migrations.AddField(
            model_name='carcasse',
            name='abattage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abattoir.abattage', verbose_name='Abattage'),
        ),
        migrations.AddField(
            model_name='carcasse',
            name='inspecteur',
            field=models.ForeignKey(limit_choices_to={'user_type': 'SUPERVISEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspecteur'),
        ),
        migrations.AddField(
            model_name='abattoir',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='abattage',
            name='bete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bete.bete', verbose_name='Bête'),
        ),
        migrations.AddField(
            model_name='abattage',
            name='operateur',
            field=models.ForeignKey(limit_choices_to={'user_type': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='abattage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abattoir.sessionabattage', verbose_name='Session'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionabattage',
            unique_together={('abattoir', 'date_session', 'heure_debut')},
        ),
        migrations.AlterUniqueTogether(
            name='abattage',
            unique_together={('session', 'ordre_abattage')},
        ),
    ]
