# Generated by Django 4.2.23 on 2025-10-25 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bete', '0002_initial'),
        ('abattoir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabulation',
            name='annule_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a annulé cette stabulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabulations_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='stabulation',
            name='betes',
            field=models.ManyToManyField(blank=True, help_text='Bêtes actuellement en stabulation', related_name='stabulations', to='bete.bete', verbose_name='Bêtes en stabulation'),
        ),
        migrations.AddField(
            model_name='stabulation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette stabulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabulations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='stabulation',
            name='finalise_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a finalisé cette stabulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabulations_finalisees', to=settings.AUTH_USER_MODEL, verbose_name='Finalisé par'),
        ),
        migrations.AddField(
            model_name='historiquechambrefroide',
            name='chambre_froide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_temperatures', to='abattoir.chambrefroide', verbose_name='Chambre froide'),
        ),
        migrations.AddField(
            model_name='historiquechambrefroide',
            name='mesure_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a enregistré cette mesure de température', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_temperature', to=settings.AUTH_USER_MODEL, verbose_name='Mesure effectuée par'),
        ),
        migrations.AddField(
            model_name='chambrefroide',
            name='abattoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres_froides', to='abattoir.abattoir', verbose_name='Abattoir'),
        ),
        migrations.AddField(
            model_name='abattoir',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abattoirs_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddIndex(
            model_name='stabulation',
            index=models.Index(fields=['abattoir', 'statut'], name='abattoir_st_abattoi_e3cab4_idx'),
        ),
        migrations.AddIndex(
            model_name='stabulation',
            index=models.Index(fields=['type_bete', 'statut'], name='abattoir_st_type_be_558f29_idx'),
        ),
        migrations.AddIndex(
            model_name='stabulation',
            index=models.Index(fields=['date_debut'], name='abattoir_st_date_de_1e946a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chambrefroide',
            unique_together={('abattoir', 'numero')},
        ),
    ]
