# Generated by Django 4.2.23 on 2025-10-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStabulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifie', models.CharField(max_length=100, verbose_name='Champ modifié')),
                ('ancienne_valeur', models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('stabulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='abattoir.stabulation', verbose_name='Stabulation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de stabulation',
                'verbose_name_plural': 'Historiques de stabulation',
                'ordering': ['-date_modification'],
            },
        ),
    ]
