# Generated by Django 4.2.23 on 2025-10-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcasse',
            name='abattage',
        ),
        migrations.RemoveField(
            model_name='carcasse',
            name='inspecteur',
        ),
        migrations.RemoveField(
            model_name='decoupe',
            name='carcasse',
        ),
        migrations.RemoveField(
            model_name='decoupe',
            name='decoupeur',
        ),
        migrations.AlterUniqueTogether(
            name='sessionabattage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionabattage',
            name='abattoir',
        ),
        migrations.RemoveField(
            model_name='sessionabattage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sessionabattage',
            name='superviseur',
        ),
        migrations.DeleteModel(
            name='Abattage',
        ),
        migrations.DeleteModel(
            name='Carcasse',
        ),
        migrations.DeleteModel(
            name='Decoupe',
        ),
        migrations.DeleteModel(
            name='SessionAbattage',
        ),
    ]
