# Generated by Django 4.2.23 on 2025-10-16 22:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0003_remove_carcasse_abattage_remove_carcasse_inspecteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChambreFroide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numéro de la chambre froide')),
                ('dimensions_m3', models.DecimalField(decimal_places=2, help_text='Volume en mètres cubes', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Dimensions (m³)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres_froides', to='abattoir.abattoir', verbose_name='Abattoir')),
            ],
            options={
                'verbose_name': 'Chambre froide',
                'verbose_name_plural': 'Chambres froides',
                'ordering': ['abattoir', 'numero'],
                'unique_together': {('abattoir', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueChambreFroide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Température en degrés Celsius', max_digits=4, verbose_name='Température (°C)')),
                ('date_mesure', models.DateTimeField(auto_now_add=True, verbose_name='Date de mesure')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chambre_froide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_temperatures', to='abattoir.chambrefroide', verbose_name='Chambre froide')),
            ],
            options={
                'verbose_name': 'Historique chambre froide',
                'verbose_name_plural': 'Historiques chambres froides',
                'ordering': ['-date_mesure'],
            },
        ),
    ]
