# Generated by Django 4.2.23 on 2025-10-16 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0004_chambrefroide_historiquechambrefroide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abattoir',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abattoirs_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
