# Generated by Django 4.2.23 on 2025-10-18 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0005_alter_abattoir_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquechambrefroide',
            name='mesure_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a enregistré cette mesure de température', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_temperature', to=settings.AUTH_USER_MODEL, verbose_name='Mesure effectuée par'),
        ),
        migrations.AddField(
            model_name='historiquechambrefroide',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes optionnelles sur cette mesure', null=True, verbose_name='Notes'),
        ),
    ]
