# Generated by Django 4.2.23 on 2025-10-18 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bete', '0004_remove_bete_date_naissance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abattoir', '0006_historiquechambrefroide_mesure_par_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abattoir',
            name='capacite_stabulation',
        ),
        migrations.AddField(
            model_name='abattoir',
            name='capacite_stabulation_bovin',
            field=models.PositiveIntegerField(default=0, help_text='Nombre maximum de bovins pouvant être en stabulation', verbose_name='Capacité de stabulation Bovin'),
        ),
        migrations.AddField(
            model_name='abattoir',
            name='capacite_stabulation_ovin',
            field=models.PositiveIntegerField(default=0, help_text="Nombre maximum d'ovins pouvant être en stabulation", verbose_name='Capacité de stabulation Ovin'),
        ),
        migrations.CreateModel(
            name='Stabulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_stabulation', models.CharField(help_text="Numéro unique d'identification de la stabulation", max_length=50, unique=True, verbose_name='Numéro de stabulation')),
                ('type_bete', models.CharField(choices=[('BOVIN', 'Bovin'), ('OVIN', 'Ovin'), ('CAPRIN', 'Caprin'), ('AUTRE', 'Autre')], help_text="Type d'animal en stabulation", max_length=20, verbose_name='Type de bête')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', help_text='Statut actuel de la stabulation', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(help_text='Date et heure de début de la stabulation', verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date et heure de fin de la stabulation (si terminée)', null=True, verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur la stabulation', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stabulations', to='abattoir.abattoir', verbose_name='Abattoir')),
                ('betes', models.ManyToManyField(blank=True, help_text='Bêtes actuellement en stabulation', related_name='stabulations', to='bete.bete', verbose_name='Bêtes en stabulation')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette stabulation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stabulations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Stabulation',
                'verbose_name_plural': 'Stabulations',
                'ordering': ['-date_debut', 'abattoir', 'numero_stabulation'],
                'indexes': [models.Index(fields=['abattoir', 'statut'], name='abattoir_st_abattoi_e3cab4_idx'), models.Index(fields=['type_bete', 'statut'], name='abattoir_st_type_be_558f29_idx'), models.Index(fields=['date_debut'], name='abattoir_st_date_de_1e946a_idx')],
            },
        ),
    ]
