# Generated by Django 4.2.23 on 2025-10-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abattoir', '0007_remove_abattoir_capacite_stabulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabulation',
            name='numero_stabulation',
            field=models.CharField(blank=True, help_text="Numéro unique d'identification de la stabulation (généré automatiquement)", max_length=50, unique=True, verbose_name='Numéro de stabulation'),
        ),
    ]
